-- Product completion: structured tasks, resubmission, profiles, and notifications.

alter table public.tasks add column if not exists title text;
alter table public.tasks add column if not exists instructions text;
alter table public.tasks add column if not exists category text;
alter table public.tasks add column if not exists deadline timestamptz;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

update public.tasks
set title = coalesce(nullif(title, ''), 'Community task #' || id::text),
    instructions = coalesce(nullif(instructions, ''), 'Complete the task according to the reference link and submit proof.'),
    category = coalesce(nullif(category, ''), 'General')
where title is null or instructions is null or category is null;

alter table public.tasks alter column title set default 'Community task';
alter table public.tasks alter column instructions set default 'Complete the task according to the reference link.';
alter table public.tasks alter column category set default 'General';

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  type text not null check (type in ('submission_approved', 'submission_rejected')),
  title text not null,
  body text not null,
  reference_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;
do $$
declare v_policy text;
begin
  for v_policy in select policyname from pg_policies
    where schemaname = 'public' and tablename = 'notifications'
  loop
    execute format('drop policy %I on public.notifications', v_policy);
  end loop;
end;
$$;
create policy "notifications_select_own" on public.notifications
  for select to authenticated using (user_id = auth.uid());
revoke all on public.notifications from anon, authenticated;
grant select on public.notifications to authenticated;

drop function if exists public.create_task(text, integer, integer);
create function public.create_task(
  p_task_url text,
  p_target integer,
  p_reward integer,
  p_title text default null,
  p_instructions text default null,
  p_category text default null,
  p_deadline timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_cost bigint;
  v_balance bigint;
  v_task_id bigint;
  v_title text := left(trim(coalesce(p_title, '')), 120);
  v_instructions text := left(trim(coalesce(p_instructions, '')), 4000);
  v_category text := left(trim(coalesce(p_category, 'General')), 60);
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_task_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'A valid http or https reference URL is required';
  end if;
  if p_target not between 1 and 10000 or p_reward not between 1 and 1000 then
    raise exception 'Target or reward is outside the allowed range';
  end if;
  if v_title = '' or v_instructions = '' then
    raise exception 'A task title and instructions are required';
  end if;
  if (select count(*) from public.transactions
      where user_id = v_user_id and type = 'task_created' and created_at > now() - interval '1 minute') >= 5 then
    raise exception 'Please wait before creating another task';
  end if;
  if p_deadline is not null and p_deadline <= now() then
    raise exception 'Deadline must be in the future';
  end if;

  v_cost := p_target::bigint * p_reward::bigint;
  select coins into v_balance from public.profiles where id = v_user_id for update;
  if not found then raise exception 'Profile not found'; end if;
  if v_balance < v_cost then raise exception 'Insufficient coin balance'; end if;

  update public.profiles set coins = coins - v_cost where id = v_user_id;
  insert into public.tasks (
    creator_id, task_url, bilibili_url, title, instructions, category, deadline, target, reward
  ) values (
    v_user_id, p_task_url, p_task_url, v_title, v_instructions, v_category, p_deadline, p_target, p_reward
  ) returning id into v_task_id;
  insert into public.transactions (user_id, amount, type, reference_id, description)
    values (v_user_id, -v_cost, 'task_created', v_task_id::text, 'Task funding: ' || v_title);
  return v_task_id;
end;
$$;

create or replace function public.submit_proof(p_task_id bigint, p_proof_url text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_proof_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'A valid http or https proof URL is required';
  end if;
  if (select count(*) from public.submissions
      where worker_id = v_user_id and created_at > now() - interval '1 hour') >= 20 then
    raise exception 'Submission limit reached; please try again later';
  end if;
  perform 1 from public.tasks
    where id = p_task_id and status = 'active' and creator_id <> v_user_id
      and completed < target and (deadline is null or deadline > now())
    for update;
  if not found then raise exception 'Task is unavailable'; end if;

  -- A rejected proof may be replaced; pending and approved proofs remain immutable.
  delete from public.submissions
    where task_id = p_task_id and worker_id = v_user_id and status = 'rejected';
  insert into public.submissions (task_id, worker_id, screenshot_url, status)
    values (p_task_id, v_user_id, p_proof_url, 'pending')
    returning id into v_submission_id;
  return v_submission_id;
exception
  when unique_violation then
    raise exception 'You already have a pending or approved submission for this task';
end;
$$;

create or replace function public.update_profile(p_username text, p_reference_url text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  p_username := left(trim(coalesce(p_username, '')), 40);
  if p_username !~ '^[A-Za-z0-9_][A-Za-z0-9 _-]{1,39}$' then
    raise exception 'Username must be 2-40 characters and use letters, numbers, spaces, underscores, or hyphens';
  end if;
  if p_reference_url is not null and p_reference_url <> '' and p_reference_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'Reference URL must use http or https';
  end if;
  update public.profiles
    set username = p_username,
        bilibili_url = nullif(trim(p_reference_url), ''),
        updated_at = now()
    where id = v_user_id;
end;
$$;

create or replace function public.approve_submission(p_submission_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission public.submissions%rowtype;
  v_task public.tasks%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_submission from public.submissions where id = p_submission_id for update;
  if not found or v_submission.status <> 'pending' then raise exception 'Submission is not pending'; end if;
  select * into v_task from public.tasks where id = v_submission.task_id for update;
  if not found or v_task.creator_id <> v_user_id then raise exception 'Only the task creator can review this submission'; end if;
  if v_task.status <> 'active' or v_task.completed >= v_task.target then raise exception 'Task is no longer available'; end if;

  update public.submissions set status = 'approved', reviewed_at = now(), admin_note = null where id = v_submission.id;
  insert into public.task_completions (task_id, worker_id) values (v_task.id, v_submission.worker_id);
  update public.tasks set completed = completed + 1,
    status = case when completed + 1 >= target then 'completed' else status end where id = v_task.id;
  update public.profiles set coins = coins + v_task.reward where id = v_submission.worker_id;
  insert into public.transactions (user_id, amount, type, reference_id, description)
    values (v_submission.worker_id, v_task.reward, 'task_approved', v_submission.id::text, 'Task reward: ' || v_task.title);
  insert into public.notifications (user_id, type, title, body, reference_id)
    values (v_submission.worker_id, 'submission_approved', 'Submission approved', 'You earned ' || v_task.reward || ' Coins for "' || v_task.title || '".', v_submission.id::text);
end;
$$;

create or replace function public.reject_submission(p_submission_id bigint, p_admin_note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission public.submissions%rowtype;
  v_task_title text;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_submission from public.submissions where id = p_submission_id for update;
  if not found or v_submission.status <> 'pending' then raise exception 'Submission is not pending'; end if;
  select title into v_task_title from public.tasks where id = v_submission.task_id and creator_id = v_user_id;
  if not found then raise exception 'Only the task creator can review this submission'; end if;
  update public.submissions set status = 'rejected', admin_note = left(nullif(trim(p_admin_note), ''), 1000), reviewed_at = now()
    where id = v_submission.id;
  insert into public.notifications (user_id, type, title, body, reference_id)
    values (v_submission.worker_id, 'submission_rejected', 'Submission needs changes', 'Your proof for "' || v_task_title || '" was rejected. You may submit a new proof.', v_submission.id::text);
end;
$$;

revoke all on function public.create_task(text, integer, integer, text, text, text, timestamptz) from public;
revoke all on function public.update_profile(text, text) from public;
grant execute on function public.create_task(text, integer, integer, text, text, text, timestamptz) to authenticated;
grant execute on function public.update_profile(text, text) to authenticated;
