-- Finish no-code content controls and add a moderated contact inbox.

alter table public.site_pages drop constraint if exists site_pages_slug_check;
alter table public.site_pages add constraint site_pages_slug_check
  check (slug in ('about', 'contact', 'disclaimer', 'privacy', 'terms'));

insert into public.site_pages(slug, title, body) values
  ('privacy', 'Privacy Notice', 'BiliFollow stores account information, task records, submission links, and internal transaction history to operate the service.'),
  ('terms', 'Terms of Use', 'BiliFollow is a platform for legitimate community tasks and internal reward points. Points have no cash value and are not Bilibili currency.')
on conflict (slug) do nothing;

create or replace function public.admin_save_site_page(p_slug text, p_title text, p_body text)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  if p_slug not in ('about', 'contact', 'disclaimer', 'privacy', 'terms') then raise exception 'Invalid page'; end if;
  p_title := left(trim(coalesce(p_title, '')), 160);
  p_body := left(trim(coalesce(p_body, '')), 10000);
  if p_title = '' or p_body = '' then raise exception 'Title and content are required'; end if;
  insert into public.site_pages(slug, title, body, updated_at, updated_by)
  values(p_slug, p_title, p_body, now(), auth.uid())
  on conflict(slug) do update set title=excluded.title, body=excluded.body, updated_at=excluded.updated_at, updated_by=excluded.updated_by;
end; $$;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  subject text not null,
  message text not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.contact_messages enable row level security;

create or replace function public.submit_contact_message(p_email text, p_subject text, p_message text)
returns void language plpgsql security definer set search_path = public as $$
begin
  p_email := left(trim(coalesce(p_email, '')), 254);
  p_subject := left(trim(coalesce(p_subject, '')), 160);
  p_message := left(trim(coalesce(p_message, '')), 4000);
  if p_email = '' or p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'A valid email is required'; end if;
  if p_subject = '' or p_message = '' then raise exception 'Subject and message are required'; end if;
  if (select count(*) from public.contact_messages where email = p_email and created_at > now() - interval '15 minutes') >= 3 then
    raise exception 'Please wait before sending another message';
  end if;
  insert into public.contact_messages(user_id, email, subject, message)
  values(auth.uid(), p_email, p_subject, p_message);
end; $$;

create or replace function public.admin_list_contact_messages(p_limit integer default 100)
returns table(id bigint, user_id uuid, email text, subject text, message text, status text, admin_note text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  return query select c.id, c.user_id, c.email, c.subject, c.message, c.status, c.admin_note, c.created_at
  from public.contact_messages c order by c.created_at desc limit greatest(1, least(coalesce(p_limit, 100), 200));
end; $$;

create or replace function public.admin_moderate_contact_message(p_message_id bigint, p_status text, p_note text default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  if p_status not in ('open', 'closed') then raise exception 'Invalid contact status'; end if;
  update public.contact_messages set status=p_status, admin_note=left(nullif(trim(coalesce(p_note, '')), ''), 2000), updated_at=now() where id=p_message_id;
  if not found then raise exception 'Contact message not found'; end if;
end; $$;

create or replace function public.admin_set_member_admin(p_user_id uuid, p_is_admin boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  if p_user_id = auth.uid() then raise exception 'You cannot change your own administrator role'; end if;
  update public.profiles set is_admin=p_is_admin where id=p_user_id;
  if not found then raise exception 'Member not found'; end if;
end; $$;

create or replace function public.admin_dashboard()
returns jsonb language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  return jsonb_build_object(
    'members', (select count(*) from public.profiles),
    'activeTasks', (select count(*) from public.tasks where status = 'active'),
    'pendingSubmissions', (select count(*) from public.submissions where status = 'pending'),
    'openReports', (select count(*) from public.reports where status in ('open', 'reviewing')),
    'openContacts', (select count(*) from public.contact_messages where status = 'open')
  );
end; $$;

revoke all on function public.submit_contact_message(text, text, text) from public;
revoke all on function public.admin_list_contact_messages(integer) from public;
revoke all on function public.admin_moderate_contact_message(bigint, text, text) from public;
revoke all on function public.admin_set_member_admin(uuid, boolean) from public;
grant execute on function public.submit_contact_message(text, text, text) to anon, authenticated;
grant execute on function public.admin_list_contact_messages(integer) to authenticated;
grant execute on function public.admin_moderate_contact_message(bigint, text, text) to authenticated;
grant execute on function public.admin_set_member_admin(uuid, boolean) to authenticated;
