-- BiliFollow: secure task, submission, and internal-points economy.
-- Apply this migration through the Supabase CLI or SQL Editor as the project owner.
-- It intentionally contains no service-role key or client secret.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null,
  coins bigint not null default 0 check (coins >= 0),
  level integer not null default 1 check (level >= 1),
  status text not null default 'active' check (status in ('active', 'suspended')),
  bilibili_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users (id) on delete cascade,
  -- task_url is the generic name. bilibili_url remains temporarily for legacy frontend compatibility.
  task_url text,
  bilibili_url text,
  target integer not null check (target between 1 and 10000),
  completed integer not null default 0 check (completed >= 0),
  reward integer not null check (reward between 1 and 1000),
  status text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  check (completed <= target)
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks (id) on delete cascade,
  worker_id uuid not null references auth.users (id) on delete cascade,
  screenshot_url text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (task_id, worker_id)
);

create table if not exists public.task_completions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks (id) on delete cascade,
  worker_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (task_id, worker_id)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  amount bigint not null check (amount <> 0),
  type text not null,
  reference_id text,
  description text,
  created_at timestamptz not null default now()
);

-- Bring a legacy database forward without renaming or dropping its old URL column.
alter table public.tasks add column if not exists task_url text;
alter table public.tasks add column if not exists bilibili_url text;
update public.tasks
set task_url = coalesce(task_url, bilibili_url),
    bilibili_url = coalesce(bilibili_url, task_url)
where task_url is null or bilibili_url is null;

create index if not exists tasks_active_created_idx
  on public.tasks (status, created_at desc);
create index if not exists submissions_task_created_idx
  on public.submissions (task_id, created_at desc);
create index if not exists submissions_worker_created_idx
  on public.submissions (worker_id, created_at desc);
create index if not exists transactions_user_created_idx
  on public.transactions (user_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
      nullif(split_part(new.email, '@', 1), ''),
      'user'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.submissions enable row level security;
alter table public.task_completions enable row level security;
alter table public.transactions enable row level security;

-- Remove any legacy policies before adding this migration's allow-list policies.
-- Table privileges below also prevent writes even if a policy is reintroduced by mistake.
do $$
declare
  v_table text;
  v_policy text;
begin
  foreach v_table in array array['profiles', 'tasks', 'submissions', 'task_completions', 'transactions']
  loop
    for v_policy in
      select policyname from pg_policies
      where schemaname = 'public' and tablename = v_table
    loop
      execute format('drop policy %I on public.%I', v_policy, v_table);
    end loop;
  end loop;
end;
$$;

create policy "profiles_select_own" on public.profiles
  for select to authenticated using (id = auth.uid());

create policy "tasks_select_active_or_owned" on public.tasks
  for select to authenticated
  using (status = 'active' or creator_id = auth.uid());

create policy "submissions_select_worker_or_creator" on public.submissions
  for select to authenticated
  using (
    worker_id = auth.uid()
    or exists (
      select 1 from public.tasks
      where tasks.id = submissions.task_id
        and tasks.creator_id = auth.uid()
    )
  );

create policy "completions_select_own" on public.task_completions
  for select to authenticated using (worker_id = auth.uid());

create policy "transactions_select_own" on public.transactions
  for select to authenticated using (user_id = auth.uid());

-- No direct INSERT, UPDATE, or DELETE policies are created for economy tables.
-- Authenticated users can read only the rows needed by the UI; RPCs perform writes.
revoke all on public.profiles, public.tasks, public.submissions,
  public.task_completions, public.transactions from anon, authenticated;
grant select on public.profiles, public.tasks, public.submissions,
  public.task_completions, public.transactions to authenticated;

create or replace function public.create_task(
  p_task_url text,
  p_target integer,
  p_reward integer
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_cost bigint;
  v_balance bigint;
  v_task_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_task_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'A valid http or https reference URL is required';
  end if;
  if p_target not between 1 and 10000 or p_reward not between 1 and 1000 then
    raise exception 'Target or reward is outside the allowed range';
  end if;

  v_cost := p_target::bigint * p_reward::bigint;
  select coins into v_balance from public.profiles where id = v_user_id for update;
  if not found then
    raise exception 'Profile not found';
  end if;
  if v_balance < v_cost then
    raise exception 'Insufficient coin balance';
  end if;

  update public.profiles set coins = coins - v_cost where id = v_user_id;
  insert into public.tasks (creator_id, task_url, bilibili_url, target, reward)
  values (v_user_id, p_task_url, p_task_url, p_target, p_reward)
  returning id into v_task_id;
  insert into public.transactions (user_id, amount, type, reference_id, description)
  values (v_user_id, -v_cost, 'task_created', v_task_id::text, 'Task funding');
  return v_task_id;
end;
$$;

create or replace function public.submit_proof(
  p_task_id bigint,
  p_proof_url text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_proof_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'A valid http or https proof URL is required';
  end if;

  perform 1 from public.tasks
    where id = p_task_id
      and status = 'active'
      and creator_id <> v_user_id
      and completed < target
    for update;
  if not found then
    raise exception 'Task is unavailable';
  end if;

  insert into public.submissions (task_id, worker_id, screenshot_url, status)
  values (p_task_id, v_user_id, p_proof_url, 'pending')
  returning id into v_submission_id;
  return v_submission_id;
exception
  when unique_violation then
    raise exception 'You have already submitted proof for this task';
end;
$$;

create or replace function public.approve_submission(p_submission_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission public.submissions%rowtype;
  v_task public.tasks%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_submission from public.submissions where id = p_submission_id for update;
  if not found or v_submission.status <> 'pending' then
    raise exception 'Submission is not pending';
  end if;
  select * into v_task from public.tasks where id = v_submission.task_id for update;
  if not found or v_task.creator_id <> v_user_id then
    raise exception 'Only the task creator can review this submission';
  end if;
  if v_task.status <> 'active' or v_task.completed >= v_task.target then
    raise exception 'Task is no longer available';
  end if;

  update public.submissions
    set status = 'approved', reviewed_at = now(), admin_note = null
    where id = v_submission.id;
  insert into public.task_completions (task_id, worker_id)
    values (v_task.id, v_submission.worker_id);
  update public.tasks
    set completed = completed + 1,
        status = case when completed + 1 >= target then 'completed' else status end
    where id = v_task.id;
  update public.profiles set coins = coins + v_task.reward where id = v_submission.worker_id;
  insert into public.transactions (user_id, amount, type, reference_id, description)
    values (v_submission.worker_id, v_task.reward, 'task_approved', v_submission.id::text, 'Task reward');
end;
$$;

create or replace function public.reject_submission(
  p_submission_id bigint,
  p_admin_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission public.submissions%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_submission from public.submissions where id = p_submission_id for update;
  if not found or v_submission.status <> 'pending' then
    raise exception 'Submission is not pending';
  end if;
  if not exists (
    select 1 from public.tasks
    where id = v_submission.task_id and creator_id = v_user_id
  ) then
    raise exception 'Only the task creator can review this submission';
  end if;
  update public.submissions
    set status = 'rejected', admin_note = left(nullif(trim(p_admin_note), ''), 1000), reviewed_at = now()
    where id = v_submission.id;
end;
$$;

revoke all on function public.create_task(text, integer, integer) from public;
revoke all on function public.submit_proof(bigint, text) from public;
revoke all on function public.approve_submission(bigint) from public;
revoke all on function public.reject_submission(bigint, text) from public;
grant execute on function public.create_task(text, integer, integer) to authenticated;
grant execute on function public.submit_proof(bigint, text) to authenticated;
grant execute on function public.approve_submission(bigint) to authenticated;
grant execute on function public.reject_submission(bigint, text) to authenticated;
