-- Private proof storage, abuse reports, admin moderation, and notification read state.

alter table public.submissions add column if not exists proof_path text;
alter table public.submissions alter column screenshot_url drop not null;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.notifications add column if not exists read_at timestamptz;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,
  submission_id bigint references public.submissions(id) on delete set null,
  category text not null check (category in ('spam', 'fraud', 'unsafe_content', 'copyright', 'other')),
  details text not null,
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  moderator_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check (task_id is not null or submission_id is not null)
);
create index if not exists reports_status_created_idx on public.reports(status, created_at desc);

alter table public.reports enable row level security;
do $$
declare v_policy text;
begin
  for v_policy in select policyname from pg_policies where schemaname = 'public' and tablename = 'reports'
  loop execute format('drop policy %I on public.reports', v_policy); end loop;
end;
$$;
create policy "reports_select_reporter_or_admin" on public.reports for select to authenticated using (
  reporter_id = auth.uid() or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
);
revoke all on public.reports from anon, authenticated;
grant select on public.reports to authenticated;

insert into storage.buckets (id, name, public)
values ('proofs', 'proofs', false)
on conflict (id) do update set public = false;

drop policy if exists "proofs_upload_own" on storage.objects;
drop policy if exists "proofs_read_owner_or_creator" on storage.objects;
drop policy if exists "proofs_delete_own" on storage.objects;
create policy "proofs_upload_own" on storage.objects for insert to authenticated with check (
  bucket_id = 'proofs' and (storage.foldername(name))[1] = auth.uid()::text
);
create policy "proofs_read_owner_or_creator" on storage.objects for select to authenticated using (
  bucket_id = 'proofs' and (
    (storage.foldername(name))[1] = auth.uid()::text
    or exists (
      select 1 from public.submissions s
      join public.tasks t on t.id = s.task_id
      where s.proof_path = storage.objects.name and t.creator_id = auth.uid()
    )
  )
);
create policy "proofs_delete_own" on storage.objects for delete to authenticated using (
  bucket_id = 'proofs' and (storage.foldername(name))[1] = auth.uid()::text
);

drop function if exists public.submit_proof(bigint, text);
create function public.submit_proof(p_task_id bigint, p_proof_path text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_submission_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_proof_path !~ '^[0-9a-f-]{36}/[A-Za-z0-9._-]{1,160}$'
    or split_part(p_proof_path, '/', 1) <> v_user_id::text then
    raise exception 'Invalid proof file path';
  end if;
  if not exists (select 1 from storage.objects where bucket_id = 'proofs' and name = p_proof_path) then
    raise exception 'Uploaded proof file was not found';
  end if;
  if (select count(*) from public.submissions where worker_id = v_user_id and created_at > now() - interval '1 hour') >= 20 then
    raise exception 'Submission limit reached; please try again later';
  end if;
  perform 1 from public.tasks
    where id = p_task_id and status = 'active' and creator_id <> v_user_id
      and completed < target and (deadline is null or deadline > now()) for update;
  if not found then raise exception 'Task is unavailable'; end if;
  delete from public.submissions where task_id = p_task_id and worker_id = v_user_id and status = 'rejected';
  insert into public.submissions (task_id, worker_id, proof_path, status)
    values (p_task_id, v_user_id, p_proof_path, 'pending') returning id into v_submission_id;
  return v_submission_id;
exception when unique_violation then
  raise exception 'You already have a pending or approved submission for this task';
end;
$$;

create or replace function public.report_content(
  p_task_id bigint default null,
  p_submission_id bigint default null,
  p_category text default 'other',
  p_details text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_user_id uuid := auth.uid(); v_report_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_task_id is null and p_submission_id is null then raise exception 'Choose content to report'; end if;
  if p_category not in ('spam', 'fraud', 'unsafe_content', 'copyright', 'other') then raise exception 'Invalid report category'; end if;
  p_details := left(trim(coalesce(p_details, '')), 2000);
  if p_details = '' then raise exception 'Please describe the problem'; end if;
  if (select count(*) from public.reports where reporter_id = v_user_id and created_at > now() - interval '1 hour') >= 10 then
    raise exception 'Report limit reached; please try again later';
  end if;
  insert into public.reports(reporter_id, task_id, submission_id, category, details)
    values(v_user_id, p_task_id, p_submission_id, p_category, p_details) returning id into v_report_id;
  return v_report_id;
end;
$$;

create or replace function public.moderate_report(
  p_report_id bigint,
  p_status text,
  p_note text default null,
  p_pause_task boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_admin_id uuid := auth.uid(); v_task_id bigint;
begin
  if v_admin_id is null or not exists (select 1 from public.profiles where id = v_admin_id and is_admin) then
    raise exception 'Administrator access required';
  end if;
  if p_status not in ('reviewing', 'resolved', 'dismissed') then raise exception 'Invalid moderation status'; end if;
  select task_id into v_task_id from public.reports where id = p_report_id for update;
  if not found then raise exception 'Report not found'; end if;
  update public.reports set status = p_status, moderator_note = left(nullif(trim(p_note), ''), 2000), reviewed_by = v_admin_id, reviewed_at = now() where id = p_report_id;
  if p_pause_task and v_task_id is not null then
    update public.tasks set status = 'cancelled' where id = v_task_id and status = 'active';
  end if;
end;
$$;

create or replace function public.mark_notifications_read()
returns void language sql security definer set search_path = public as $$
  update public.notifications set read_at = now() where user_id = auth.uid() and read_at is null;
$$;

revoke all on function public.submit_proof(bigint, text) from public;
revoke all on function public.report_content(bigint, bigint, text, text) from public;
revoke all on function public.moderate_report(bigint, text, text, boolean) from public;
revoke all on function public.mark_notifications_read() from public;
grant execute on function public.submit_proof(bigint, text) to authenticated;
grant execute on function public.report_content(bigint, bigint, text, text) to authenticated;
grant execute on function public.moderate_report(bigint, text, text, boolean) to authenticated;
grant execute on function public.mark_notifications_read() to authenticated;
